name: Test and build
on:
  push:
    paths-ignore:
      - website/**
    branches:
      - main
  pull_request:
    paths-ignore:
      - website/**
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    name: Setup repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup repository
        uses: ./.github/actions/setup-repository
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint the codebase
        uses: ./.github/actions/lint

  build:
    name: Build and check types
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build script
        uses: ./.github/actions/build

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [ build ]
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup repository
        uses: ./.github/actions/setup-repository

      - name: Run tests
        run: npm test
  
  publish_nightly:
    name: Publish nightly build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    needs: [ build ]
    if: github.ref == 'refs/heads/main' && github.repository == 'nandertga/msgroom-orm'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup repository
        uses: ./.github/actions/setup-repository

      - name: Bump version
        run: npm version prerelease
      
      - name: Push the new version
        run: git push origin main
      
      - name: Publish the nightly build to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_MSGROOM }}
        run: npm publish --provenance --tag nightly
