# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to npm on release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish_releases:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Generate a tarball from the build results
        if: '!cancelled()'
        run: npm pack

      - name: Upload the tarball as an artifact
        if: '!cancelled()'
        uses: actions/upload-artifact@v3
        with:
          path: msgroom-*.tgz

      - name: Publish the nightly build to npm
        if: '!cancelled()'
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_MSGROOM }}
