name: Test and build
on:
  push:
  pull_request:

jobs:
  test_and_build:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Setup git configuration
        run: |
          git config user.name "Github Actions Bot"
          git config user.email "<>"

      - name: Bump version
        if: ${{ !cancelled() && env.NODE_AUTH_TOKEN != '' }}
        run: npm version prerelease
      
      - name: Push the new version
        run: git push origin master

      - name: Run tests
        run: npm test

      - name: Generate a tarball from the build results
        if: '!cancelled()'
        run: npm pack

      - name: Upload the tarball as an artifact
        if: '!cancelled()'
        uses: actions/upload-artifact@v3
        with:
          path: msgroom-*.tgz

      - name: Publish the nightly build to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_MSGROOM }}
        if: ${{ !cancelled() && env.NODE_AUTH_TOKEN != '' }}
        run: npm publish --provenance --tag nightly
      
      - name: Send warn if there's no NPM token provided
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_MSGROOM }}
        if: ${{ !cancelled() && env.NODE_AUTH_TOKEN == '' }}
        run: echo "::warning::No NPM token provided"
