name: Test and build
on:
  push:
    paths:
      - src/**
      - package.json
      - tsconfig.json
      - .github/workflows/**
      - README.md
    branches:
      - main
  pull_request:
    paths:
      - src/**
      - package.json
      - tsconfig.json
      - .github/workflows/**
      - README.md
    branches:
      - main

jobs:
  test_and_build:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Setup git configuration
        run: |
          git config user.name "Github Actions Bot"
          git config user.email "<>"

      - name: Bump version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_MSGROOM }}
        if: ${{ !cancelled() && env.NODE_AUTH_TOKEN != '' }}
        run: npm version prerelease
      
      - name: Push the new version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_MSGROOM }}
        if: ${{ !cancelled() && env.NODE_AUTH_TOKEN != '' }}
        run: git push origin main

      - name: Run tests
        run: npm test

      - name: Generate a tarball from the build results
        if: '!cancelled()'
        run: npm pack

      - name: Upload the tarball as an artifact
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          path: msgroom-*.tgz

      - name: Publish the nightly build to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_MSGROOM }}
        if: ${{ !cancelled() && env.NODE_AUTH_TOKEN != '' }}
        run: npm publish --provenance --tag nightly
